---
language: bash

services:
  - docker

cache: $TRAVIS_CACHE

# Only build on master
branches:
  only:
    - master

stages:
  - build

jobs:
  include:
    - stage: build
      name: Build amd64 image
      os: linux
      arch: amd64
      services:
        - docker
      script:
        - sudo apt update
        - sudo apt -y install unzip
        - docker build -t quay.io/opencloudio/ibm-common-service-catalog:ashank-test -f Dockerfile.test .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
        - docker push quay.io/opencloudio/ibm-common-service-catalog:ashank-test
        
notifications:
  email: false
